### PR TITLE
Alumni update 21

### PR DESCRIPTION
**Pull request by kylemtam**
Gist of the update: Moved all the '21 grads to the alumni section and also revamped that section so the program names are clearer (given that soon we'll have non-eng programs). Also updated some project lead titles.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/132)

### CODE REVIEW

**Review by QuantumManiac — APPROVED** [review]
LGTM! Should we move members with lead roles to the top? I don't recall if we usually do that or not.

**Review by chrissank — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/132)* status: all files reviewed, 1 unresolved discussion (waiting on @kylemtam and @wendi-yu)

*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/website/132#-MdKJwLWDvo26rtS6iVB:-MdKJwLWDvo26rtS6iVC:b-9opvx0) (no related file):*
Other than updating my title, :lgtm: 

---

**Comment by kylemtam** [comment]
Rip sorry Chris, I thought I updated your title, but apparently not!

in response to @QuantumManiac , we usually don't put the project leads on the top, tho that was more a quirk of Jacob's and his love of tradition than anything. Now that he's gone, I'm open to reconsidering it. Thoughts?

**Comment by kylemtam** [comment]
Our glorious leader Wendi has spoken and now project leads are on top. Blessed be Yu.

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/132)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @chrissank)

*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/website/132#-MdKJwLWDvo26rtS6iVB:-Me2X0Y6AU_p0skQtpJ9:bg7igkv) (no related file):*
<details><summary><i>Previously, chrissank (Chris Sankey) wrote…</i></summary><blockquote>

Other than updating my title, :lgtm: 
</blockquote></details>

:lgtm: 

---

**Review by wendi-yu — APPROVED** [review]

**Pull request merged**
