### PR TITLE
Members update 2021

### PR DESCRIPTION
**Pull request by kylemtam**
This was a big update for the team members page - probably the biggest we've ever done - so I likely have missed a few things :)

Spreadsheet can be found here for reference: 
[https://docs.google.com/spreadsheets/d/1OhANTTXS00mJcnI6krWE5CQDB5j4x338YweHgBvXB1A/edit?usp=sharing]

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/130)

### CODE REVIEW

**Comment by jacobdeery** [comment]
Michael is still overflowing:

image

**Comment by wendi-yu** [comment]
Fixed the overflowing

**Review by wendi-yu — APPROVED** [review]
I'm unsure if this is like, legal for me to review but the parts that I didn't do :lgtm: checked spellings and images for the new members

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/130#-:-MTbwTBIE4JfTVFHOCt8:b-hepamc)* status: 0 of 23 files reviewed, all discussions resolved (waiting on @jacobdeery)

**Comment by jacobdeery** [comment]
I didn't spend any time trying to figure out where the issue is, but there's a bunch of random whitespace around the div at the bottom:

image

**Comment by kylemtam** [comment]
I think I fixed it - a missing `</div>` was missing

**Review by jacobdeery — APPROVED** [review]
Looks good to me!

**Pull request merged**
