### PR TITLE
Fix indents and remove whitespace

### LINKED ISSUE #95: Prettify everything
There's a lot of inconsistent indentation and there's probably some trailing whitespace still floating around somewhere. A pass with a formatter would be good. Ideally, we'd have a format script that we could just run whenever we want, but that might be a bit too ambitious.

### PR DESCRIPTION
**Pull request by wendi-yu**

### CODE REVIEW

**Comment by wendi-yu** [comment]
I popped the files into an online HTML prettifier and copied them back in so it looks like I changed everything but I didn't actually :0

**Review by akmorrison — APPROVED** [review]
`git diff --ignore-all-space --ignore-blank-lines prettify gh-pages` shows four non-whitespace diffs, all of which are breaking single lines into multiple lines. Can confirm no content changes.
(the four are line 38 and 43 in index.html, and line 46 in vidar2.html, and 45 in vidar3.html)

I'd prefer a script based solution that we can run pre commit, but this works too.

**Review by jacobdeery — APPROVED** [review]
There doesn't seem to be a widely used HTML formatting tool that we could script, from what I can tell. I would also love something like clang-format, but this is fine for now.

The only thing I might change with this is adding newlines back to the end of each file; it looks like when you copypasted, those went away.

Enjoy being `blame`d for everything!

**Comment by wendi-yu** [comment]
I kinda looked into that briefly, there's this HTML tidy thing that seems to be what we want?
http://www.html-tidy.org/documentation/

**Pull request merged**
