### PR TITLE
Add UXO drawing

### LINKED ISSUE #63: UXO drawing
There is none.

### PR DESCRIPTION
**Pull request by kylemtam**
Close #63

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/123)

### CODE REVIEW

**Review by jacobdeery — APPROVED** [review]
This is _awesome_. Thanks Shahed!

**Review by jacobdeery — CHANGES_REQUESTED** [review]
Wait, hold on. Can you use a PNG instead of a JPG?

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/123#-:-MJPDGFWE4DrGaBG0RpO:b-bx5wyk)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @wendi-yu)

**Review by kylemtam — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/123#-:-MJPoj7Q2rJWOntzGvI4:b-896fix)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @wendi-yu)

**Comment by jacobdeery** [comment]
It looks like the image still has JPG compression artifacts in it. Could you ask Shahed to export the original drawing as a PNG so that it's nice and crisp?

image

**Comment by kylemtam** [comment]
Sorry for the wait. It should be done now

**Review by jacobdeery — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wendi-yu)

**Review by jacobdeery — APPROVED** [review]

**Pull request merged**
