### PR TITLE
Update sponsors

### PR DESCRIPTION
**Pull request by wendi-yu**
Didn't downgrade SolidWorks because Shirley said in Slack that the sponsorship tracker just hasn't been updated. I also wanted to check about downgrading the faculty of engineering, will modify if they are supposed to be gold.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/126)

### CODE REVIEW

**Review by kylemtam — COMMENTED** [review]
I think the sponsorship tracker is not up to date for MEF, but I believe it should be in a higher tier.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/126#-:-MOT-EnC1B3D1yGxclvu:boyidwj)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jacobdeery and @kylemtam)

**Review by jacobdeery — COMMENTED** [review]
Agreed that MEF should move to Gold. Let's keep Eng at platinum for now until we confirm what happened with Dean's funding.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/126#-:-MPgnC7N1rkQC9HVJa0S:bebdlf5)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jacobdeery and @wendi-yu)

___
*[sponsors.html, line 210 at r1](https://reviewable.io/reviews/waterloo-rocketry/website/126#-MPgmILh4hrgn28TIdDQ:-MPgmILh4hrgn28TIdDR:bi7sv42) ([raw file](https://github.com/waterloo-rocketry/website/blob/d4b74bfe59f1ed292a6e5ee0bd14f23e41086abb/sponsors.html#L210)):*
> ```HTML
>                 <a href="http://www.praxair.ca/splash/" target="_blank">
>                 
>                 </a>				
> ```

You somehow managed to add _more_ trailing whitespace to this line.

**Comment by kylemtam** [comment]
I added in a description for MEF. Also I updated the description for Hatch (the second line was weird), mentioning way more awards they've won since 2015.

**Review by wendi-yu — COMMENTED** [review]
I don't think reviewable will let me approve my PR but Kyle's changes LGTM :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/126#-:-MPk9IAF09X-rKsYG4ei:bykohrq)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jacobdeery)

___
*[sponsors.html, line 210 at r1](https://reviewable.io/reviews/waterloo-rocketry/website/126#-MPgmILh4hrgn28TIdDQ:-MPk9Gnl8QuLOmxKLfEy:bqyjyg) ([raw file](https://github.com/waterloo-rocketry/website/blob/d4b74bfe59f1ed292a6e5ee0bd14f23e41086abb/sponsors.html#L210)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

You somehow managed to add _more_ trailing whitespace to this line.
</blockquote></details>

Looks like this is fixed

**Review by jacobdeery — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/126)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jacobdeery)

**Pull request merged**
