### PR TITLE
Sponsor update

### PR DESCRIPTION
**Pull request by wendi-yu**
Updated sponsors:
- added Broadcom, Mitutoyo, Aircraft Spruce, A&P
- moved solidworks to platinum
- moved engsoc from gold to bronze

Also fixed a broken youtube logo

### CODE REVIEW

**Review by AidanHa — APPROVED** [review]

**Comment by AidanHa** [comment]
@jacobdeery Not sure if you want to merge this one since idk if you were the one to assign this PR

**Review by jacobdeery — COMMENTED** [review]
Thanks Wendi! Looks good in general; just a few changes before this one's ready to merge.

- Dutton-Lainson and Richard Dudgeon's sponsorships have expired, so they should be moved to Previous Sponsors
- Hickory Hill Communications is also a new Bronze sponsor (they weren't on the tracker; my fault). Their logo is on the drive (Sponsorship and Finances -> Sponsor Logos)
- There's a decent gap between the 3rd and 4th rows of Bronze sponsors (shown below). It looks like this is coming from the Broadcom logo, which has a bunch of empty space in the actual image. Cropping this whitespace out should fix the gap
image
- I think it would look a bit cleaner if Keysight and Solidworks were in the same row rather than having their own rows (would match up with WEEF/Faculty of Eng).

**Comment by wendi-yu** [comment]
Alright I touched up on the things you mentioned, should be good now! Let me know if it needs any other changes :)
Also forgot to mention last time but I modified the sponsor links so that the company pages would open in a new tab, which seemed a bit more intuitive?

**Review by jacobdeery — APPROVED** [review]
Looks great! Thank you for doing this.

Today I learned about `target="_blank"`. Great change!

**Pull request merged**
