### PR TITLE
Update members s20

### PR DESCRIPTION
**Pull request by kylemtam**
- Move Alex, Doris, Vithusan and Stefan to alumi section
- Update titles for Shirley, Tom, Jacob, Hamza
- Add Chris and Derek
- Decrease font size in alumni section to fit Vithusan's name

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/112)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/112)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jacobdeery, @kylemtam, and @wendi-yu)

___
*[team.html, line 81 at r1](https://reviewable.io/reviews/waterloo-rocketry/website/112#-M9f6QHk--Rh1vYc0wS8:-M9f6QHk--Rh1vYc0wS9:bpkgpag) ([raw file](https://github.com/waterloo-rocketry/website/blob/3facd46f5a33a02fb9b11cdd5d96c6deaeafce88/team.html#L81)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>             <div class="col-sm-2 box__outer" id="riley">
>                 <div class="box__inner">
>                     <h1>Riley Holierhoek</h1>
>                     <h2>Media</h2>
>                 </div>
>             </div>
> ```
</details>


Should Riley be removed?
___
*[team.html, line 279 at r1](https://reviewable.io/reviews/waterloo-rocketry/website/112#-M9f7GPz6hBkNeYkmpyt:-M9f7GPz6hBkNeYkmpyu:boys6p1) ([raw file](https://github.com/waterloo-rocketry/website/blob/3facd46f5a33a02fb9b11cdd5d96c6deaeafce88/team.html#L279)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
>             <div class="col-sm-2 box__outer" id="chriss">
>                 <div class="box__inner">
>                     <h1>Chris Sankey</h1>
>                     <h2>Recovery Member</h2>
>                 </div>
>             </div>
>             <div class="col-sm-2 box__outer" id="derek">
>                 <div class="box__inner">
>                     <h1>Derek Wu</h1>
>                     <h2>Member</h2>
>                 </div>
>             </div>
> ```
</details>


We typically order people by date joined. Is this accurate for Chris and Derek?

**Review by kylemtam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/112)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[team.html, line 81 at r1](https://reviewable.io/reviews/waterloo-rocketry/website/112#-M9f6QHk--Rh1vYc0wS8:-M9fMLf_9ZqIi7C78i57:bqb85zt) ([raw file](https://github.com/waterloo-rocketry/website/blob/3facd46f5a33a02fb9b11cdd5d96c6deaeafce88/team.html#L81)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>             <div class="col-sm-2 box__outer" id="riley">
>                 <div class="box__inner">
>                     <h1>Riley Holierhoek</h1>
>                     <h2>Media</h2>
>                 </div>
>             </div>
> ```

Should Riley be removed?
</blockquote></details>

I was thinking about it but I don't think so. Riley only recently left and he may return next term after he gets his life under control. I was planning on doing only one annual culling around Feb (plus then we'd have to delete some other people like Veronica, etc. who have been inactive)
___
*[team.html, line 279 at r1](https://reviewable.io/reviews/waterloo-rocketry/website/112#-M9f7GPz6hBkNeYkmpyt:-M9fMDMc-y_p-CjEZjO4:bxgwh6x) ([raw file](https://github.com/waterloo-rocketry/website/blob/3facd46f5a33a02fb9b11cdd5d96c6deaeafce88/team.html#L279)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>             <div class="col-sm-2 box__outer" id="chriss">
>                 <div class="box__inner">
>                     <h1>Chris Sankey</h1>
>                     <h2>Recovery Member</h2>
>                 </div>
>             </div>
>             <div class="col-sm-2 box__outer" id="derek">
>                 <div class="box__inner">
>                     <h1>Derek Wu</h1>
>                     <h2>Member</h2>
>                 </div>
>             </div>
> ```

We typically order people by date joined. Is this accurate for Chris and Derek?
</blockquote></details>

Switched Chris and Nadine. Should be fixed

**Review by wendi-yu — CHANGES_REQUESTED** [review]
I think Jacob mentioned in passing that the team cover pic could use updating since it's from like, 2017 - this seems like a good time to do that if we want to?

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/112#-:-M9gPRgI0NnIIt5eRZ_9:bbalhxo)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @jacobdeery, @kylemtam, and @wendi-yu)

___
*[team.html, line 259 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/112#-M9gNcGC6yhKLHODv5u5:-M9gNcGC6yhKLHODv5u6:b-jj411j) ([raw file](https://github.com/waterloo-rocketry/website/blob/fef0e7571f181a2204425a9f8cb06ee4fc714075/team.html#L259)):*
> ```HTML
>                 <div class="box__inner">
>                     <h1>Wendi Yu</h1>
>                     <h2>Electrical</h2>
> ```

If this is _the_ member update do we mind changing me to Software/Electrical :0 (I can also just do it myself if Kyle doesn't mind my grubby fingers on his PR lol)
___
*[css/team.css, line 412 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/112#-M9gPFqz5soh0KuR6bhF:-M9gPFqz5soh0KuR6bhG:bkwjop3) ([raw file](https://github.com/waterloo-rocketry/website/blob/fef0e7571f181a2204425a9f8cb06ee4fc714075/css/team.css#L412)):*
> ```CSS
>     background: url('../images/members/derek.jpg');
>     background-size: cover;	
> }
> ```

Missing final newline (though I think it was missing before too)

**Review by kylemtam — COMMENTED** [review]
I've chosen a new photo that looks welcoming and chill. Let me know if there is any venomous opposition to it.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/112#-:-M9lIQqD28pRd7fxu1KK:b-d8d0jv)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[team.html, line 259 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/112#-M9gNcGC6yhKLHODv5u5:-M9lI_ngDtmO9UG-DLHM:b779w2s) ([raw file](https://github.com/waterloo-rocketry/website/blob/fef0e7571f181a2204425a9f8cb06ee4fc714075/team.html#L259)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

If this is _the_ member update do we mind changing me to Software/Electrical :0 (I can also just do it myself if Kyle doesn't mind my grubby fingers on his PR lol)
</blockquote></details>

It is not _the_ update (I was not advertising this) but done
___
*[css/team.css, line 412 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/112#-M9gPFqz5soh0KuR6bhF:-M9lKYDQ7PKHJ72pVgHI:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/fef0e7571f181a2204425a9f8cb06ee4fc714075/css/team.css#L412)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Missing final newline (though I think it was missing before too)
</blockquote></details>

Done.

**Review by jacobdeery — APPROVED** [review]
Stay hydrated kids

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/112#-:-M9n2nhy459nylFNMu7f:b-jppuna)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

**Review by wendi-yu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/112#-:-M9qRzrIBQLXJmzFSpkm:bnfp4nl)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jacobdeery)

**Review by kittykong5124 — APPROVED** [review]
LGTM!

**Pull request merged**
